### ISSUE TITLE
Intermitent timeout

### ISSUE THREAD

**Issue by niceperl** [oklahomer/p5-Facebook-OpenGraph#23]
From time to time (unknow reason), I get this exception:

> `Internal Response: Cannot connect to graph.facebook.com:443: timeout at /(...)/perl-5.28.1/lib/site_perl/5.28.1/Facebook/OpenGraph.pm line 493`

It occurs in about 1% of calls, and I am sure it's not related to this great module. 
Is there any way to increase the timeout value?

**Comment by oklahomer** [comment]
One way to customize the timeout setting is to initialize `Furl::HTTP` by yourself. 
ref. https://metacpan.org/pod/Furl::HTTP#timeout-:Int-=-10
What `Facebook::OpenGraph` does is that when no `Furl::HTTP` is passed on `new()`, it [initializes `Furl::HTTP` and sets its instance](https://metacpan.org/source/OKLAHOMER/Facebook-OpenGraph-1.25/lib/Facebook/OpenGraph.pm#L35-38) instead of you. You can explicitly setup `Furl::HTTP` with larger timeout setting and pass it to `new()` to replace the default instance.

**Comment by oklahomer** [comment]
Closing as issuer reacted with a thumb up.
@niceperl Feel free to reopen this or open an issue when any further confirmation is required.
